spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/users/**
        - id: catalog
          uri: lb://APPLICATION-CATALOG
          predicates:
            - Path=/catalogs/**
        - id: order
          uri: lb://APPLICATION-ORDER
          predicates:
            - Path=/orders/**